export interface Options {
    quick: boolean,
    updateAdvisor: boolean,
    minCVSSForIssue: number,
    url: string,
    github_token: string,
    createIssues: boolean,
    failOnCVSS: number,
    path: string,
    debug: boolean,
    "skip-collectors": Array<string>
}

export const collectors = [
    "maven"	,
"gradle",
"ant",
"jar",
"sbt",	
"glide"	,
"go get",
"go mod",
"godep",
"dep",
"govendor",
"trash",
"pip"	,
"pipenv",
"bower"	,
"yarn",
"npm",
"cocoapods",	
"gem",
"composer"	,
"makefile"	,
"dll",
"msbuilddotnet",
]